In [200]:
import pandas as pd

In [201]:
items = {
    "Name":["Adway", "D", "Abhishek"],
    "Age" :[22, 21,19]
}
df = pd.DataFrame(items)
(df)

       Name  Age
0     Adway   22
1         D   21
2  Abhishek   19

In [202]:
# 1. Series

srs = pd.Series([22,21,18], index=["A", "B", "C"])
print(srs)
# print(srs["A"])

A    22
B    21
C    18
dtype: int64

In [203]:
# Properties
# 1 Homogenous
s = pd.Series([21,22,"Adway"], index=["A", "B", 22])

# 2 Vectorization operations
s1=pd.Series([1,2,3])
s2=pd.Series([10,20,30])
print("Add 2 series")
print(s1+s2)
s1[2]=9
s1

# 3 Immutable size if we add or delete new series is created
print("drop")
change=s1.drop(0) # series is not changet, so we have to create new series
change

Add 2 series
0    11
1    22
2    33
dtype: int64
drop

1    2
2    9
dtype: int64

In [204]:
# 2. DataFrame

items = {
    "Name":["Adway", "D", "Abhishek"],
    "Age" :[22, 21,19]
}
df=pd.DataFrame(items)
df
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age'], dtype='str')

In [205]:
df=pd.DataFrame([["Adway",22,9.1], ["D",18,9.2],["Abhishek",21,9.3]], 
                columns=["Name", "Age", "CGPA"], 
                index=[1,2,3])
df

       Name  Age  CGPA
1     Adway   22   9.1
2         D   18   9.2
3  Abhishek   21   9.3

In [206]:
import numpy as np
np_lst = np.array([[1,2,3], [4,5,6]])
df = pd.DataFrame(np_lst, columns=["A", "B", "C"], index=[1,2])
print(df)

   A  B  C
1  1  2  3
2  4  5  6

In [207]:
df = pd.read_csv("business.csv")
# print(df.head(2))
# print(df.tail(2))
# print(df.info())
# print(df.shape)
# print(df.sample(3))
# print(df.columns)
# print(df.nunique)
# print(df.describe())

In [208]:
df = pd.read_csv("global_air_quality_data_10000.csv")
# df.describe()

# ---selecting rows and columns---

# df[["City", "Country"]]
# df.loc[0:3]
# df.loc[1:6, ["Country","Temperature"]]
df.iloc[0:3,0:4]
df.at[0,"City"]
df.columns
change=df["City"].copy()
df["City"]
# df.isnull().sum()

0              Bangkok
1             Istanbul
2       Rio de Janeiro
3               Mumbai
4                Paris
             ...
9995      Johannesburg
9996            Berlin
9997            Moscow
9998            Berlin
9999           Bangkok
Name: City, Length: 10000, dtype: str

In [209]:
# Filtering data 

temp = df[(df["Temperature"]>39 )& (df["Humidity"]>90)] [["City", "Country"]]
temp.iloc[5]
# temp

City       Rio de Janeiro
Country            Brazil
Name: 3000, dtype: str

In [210]:
# query


new = df.query("Temperature>20")[["City", "Country"]]  # view version
new = df.query("Temperature>20")[["City", "Country"]].copy()  #creates copy

In [211]:
# Cleaning Data 

df = pd.read_csv("raw_data.csv")
# df.isnull().sum()  #or isna()
# df.dropna()
# df.dropna(axis=1)
# df.fillna(99)
age_mean=df["age"].mean()
df["age"].fillna(age_mean)

# creating copy 

# cleaned=df.copy()
# age_mean=cleaned["age"].mean()
# cleaned["age"] = cleaned["age"].fillna(age_mean)
# cleaned
df.ffill()  #previous value is given to next one from top to bottom
df.bfill()  #previous value is given to next one from bottom to top

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [212]:
#Duplicate Handling

df["income"].duplicated()
df.drop_duplicates()
df2=df.copy()
df.drop_duplicates(inplace=True)

In [213]:
# Handling Data Type 

df.dtypes
df2=df.copy()
df2 =df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

# Date Time 
pd.to_datetime("2003-11-30")

# Handling string 
df["gender"].str.capitalize()
df["name"].str.split()
# df["name"].str.split("@")   for separating name from email
df["country"].str.contains("india", case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: country, dtype: bool